// --------------------------------------------------------
// Generated by glux perl script ()
// 
// Sylvain Lefebvre - 2002 - Sylvain.Lefebvre@imag.fr
// --------------------------------------------------------
#ifndef __GLUX_LOAD_ALL__
#define __GLUX_LOAD_ALL__
// --------------------------------------------------------
#include <glux.h>
// --------------------------------------------------------
 GLUX_LOAD(GL_EXT_provoking_vertex)
 GLUX_LOAD(GL_ATI_text_fragment_shader)
 GLUX_LOAD(GL_EXT_compiled_vertex_array)
 GLUX_LOAD(GL_NV_vertex_attrib_integer_64bit)
 GLUX_LOAD(GL_ARB_vertex_array_bgra)
 GLUX_LOAD(GL_NV_gpu_shader5)
 GLUX_LOAD(GL_AMD_pinned_memory)
 GLUX_LOAD(GL_NV_transform_feedback)
 GLUX_LOAD(GL_EXT_packed_depth_stencil)
 GLUX_LOAD(GL_APPLE_element_array)
 GLUX_LOAD(GL_EXT_multisample)
 GLUX_LOAD(GL_EXT_cull_vertex)
 GLUX_LOAD(GL_EXT_draw_range_elements)
 GLUX_LOAD(GL_NV_light_max_exponent)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_ARB_create_context_profile)
#endif
 GLUX_LOAD(GL_IBM_cull_vertex)
 GLUX_LOAD(GL_ARB_half_float_pixel)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_OML_swap_method)
#endif
 GLUX_LOAD(GL_NV_fragment_program4)
 GLUX_LOAD(GL_KHR_texture_compression_astc_ldr)
 GLUX_LOAD(GL_SGIX_ycrcba)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_pbuffer)
#endif
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_ARB_create_context)
#endif
 GLUX_LOAD(GL_ARB_texture_rgb10_a2ui)
 GLUX_LOAD(GL_INTEL_parallel_arrays)
 GLUX_LOAD(GL_NV_occlusion_query)
 GLUX_LOAD(GL_NV_multisample_filter_hint)
 GLUX_LOAD(GL_APPLE_vertex_program_evaluators)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_extensions_string)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_gamma)
#endif
 GLUX_LOAD(GL_SGIX_texture_coordinate_clamp)
 GLUX_LOAD(GL_EXT_vertex_weighting)
 GLUX_LOAD(GL_SGIX_scalebias_hint)
 GLUX_LOAD(GL_ARB_point_parameters)
 GLUX_LOAD(GL_ARB_depth_buffer_float)
 GLUX_LOAD(GL_ARB_vertex_array_object)
 GLUX_LOAD(GL_SUN_convolution_border_modes)
 GLUX_LOAD(GL_ATI_texture_mirror_once)
 GLUX_LOAD(GL_ATI_fragment_shader)
 GLUX_LOAD(GL_EXT_texture_filter_anisotropic)
 GLUX_LOAD(GL_ARB_separate_shader_objects)
#ifdef WIN32
 GLUX_LOAD(WGL_3DL_stereo_control)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_NV_float_buffer)
#endif
 GLUX_LOAD(GL_EXT_texture_snorm)
 GLUX_LOAD(GL_AMD_query_buffer_object)
 GLUX_LOAD(GL_APPLE_fence)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_pixel_format_packed_float)
#endif
 GLUX_LOAD(GL_INGR_blend_func_separate)
 GLUX_LOAD(GL_ARB_multitexture)
 GLUX_LOAD(GL_ARB_shading_language_packing)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_video_capture)
#endif
 GLUX_LOAD(GL_APPLE_flush_buffer_range)
 GLUX_LOAD(GL_EXT_multi_draw_arrays)
 GLUX_LOAD(GL_SGIX_texture_select)
 GLUX_LOAD(GL_ARB_shader_bit_encoding)
 GLUX_LOAD(GL_ARB_provoking_vertex)
 GLUX_LOAD(GL_ARB_copy_image)
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_digital_video_control)
#endif
 GLUX_LOAD(GL_EXT_copy_texture)
 GLUX_LOAD(GL_EXT_rescale_normal)
 GLUX_LOAD(GL_EXT_bgra)
 GLUX_LOAD(GL_EXT_polygon_offset)
 GLUX_LOAD(GL_NV_fragment_program)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_MESA_set_3dfx_mode)
#endif
 GLUX_LOAD(GL_ARB_compressed_texture_pixel_storage)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGI_cushion)
#endif
 GLUX_LOAD(GL_ARB_texture_cube_map)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_multisample_coverage)
#endif
 GLUX_LOAD(GL_EXT_pixel_transform)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_create_context_es2_profile)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_NV_present_video)
#endif
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_visual_select_group)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_NV_swap_group)
#endif
 GLUX_LOAD(GL_EXT_texture_compression_latc)
 GLUX_LOAD(GL_ARB_transform_feedback3)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_NV_video_out)
#endif
 GLUX_LOAD(GL_NV_copy_depth_to_color)
 GLUX_LOAD(GL_EXT_texture_swizzle)
 GLUX_LOAD(GL_ARB_shading_language_420pack)
 GLUX_LOAD(GL_APPLE_aux_depth_stencil)
 GLUX_LOAD(GL_MESA_pack_invert)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIS_blended_overlay)
#endif
 GLUX_LOAD(GL_INGR_interlace_read)
 GLUX_LOAD(GL_SGIX_calligraphic_fragment)
 GLUX_LOAD(GL_SGIX_tag_sample_buffer)
 GLUX_LOAD(GL_ARB_texture_gather)
 GLUX_LOAD(GL_EXT_blend_equation_separate)
 GLUX_LOAD(GL_SGIX_list_priority)
 GLUX_LOAD(GL_NV_vertex_program4)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_buffer_age)
#endif
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_ARB_get_proc_address)
#endif
 GLUX_LOAD(GL_ARB_framebuffer_no_attachments)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGI_make_current_read)
#endif
 GLUX_LOAD(GL_EXT_gpu_program_parameters)
 GLUX_LOAD(GL_3DFX_tbuffer)
 GLUX_LOAD(GL_ARB_ES2_compatibility)
 GLUX_LOAD(GL_ARB_internalformat_query)
 GLUX_LOAD(GL_APPLE_texture_range)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_ARB_fbconfig_float)
#endif
 GLUX_LOAD(GL_NV_geometry_shader4)
 GLUX_LOAD(GL_EXT_index_material)
 GLUX_LOAD(GL_SGIX_vertex_preclip)
 GLUX_LOAD(GL_EXT_framebuffer_sRGB)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_framebuffer_sRGB)
#endif
 GLUX_LOAD(GL_AMD_conservative_depth)
 GLUX_LOAD(GL_APPLE_vertex_array_range)
 GLUX_LOAD(GL_ARB_point_sprite)
 GLUX_LOAD(GL_WIN_specular_fog)
 GLUX_LOAD(GL_NV_point_sprite)
 GLUX_LOAD(GL_ARB_shader_subroutine)
 GLUX_LOAD(GL_SGIS_detail_texture)
 GLUX_LOAD(GL_SGIX_pixel_texture)
 GLUX_LOAD(GL_SGIX_texture_lod_bias)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_framebuffer_sRGB)
#endif
 GLUX_LOAD(GL_SGIX_fog_offset)
 GLUX_LOAD(GL_SGIX_pixel_tiles)
 GLUX_LOAD(GL_NV_depth_clamp)
 GLUX_LOAD(GL_SGIS_texture_select)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_MESA_agp_offset)
#endif
 GLUX_LOAD(GL_NV_texgen_emboss)
 GLUX_LOAD(GL_3DFX_multisample)
 GLUX_LOAD(GL_AMD_shader_stencil_export)
 GLUX_LOAD(GL_SUN_vertex)
 GLUX_LOAD(GL_ARB_vertex_program)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_NV_present_video)
#endif
 GLUX_LOAD(GL_NV_multisample_coverage)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_multisample)
#endif
 GLUX_LOAD(GL_SGIX_texture_scale_bias)
 GLUX_LOAD(GL_ARB_half_float_vertex)
 GLUX_LOAD(GL_ARB_get_program_binary)
 GLUX_LOAD(GL_APPLE_transform_hint)
 GLUX_LOAD(GL_EXT_index_texture)
 GLUX_LOAD(GL_ARB_occlusion_query2)
 GLUX_LOAD(GL_ARB_timer_query)
 GLUX_LOAD(GL_EXT_packed_float)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_MESA_copy_sub_buffer)
#endif
 GLUX_LOAD(GL_SGIX_blend_alpha_minmax)
 GLUX_LOAD(GL_ATI_pixel_format_float)
 GLUX_LOAD(GL_S3_s3tc)
 GLUX_LOAD(GL_ATI_element_array)
 GLUX_LOAD(GL_ARB_draw_buffers_blend)
 GLUX_LOAD(GL_AMD_depth_clamp_separate)
 GLUX_LOAD(GL_ARB_base_instance)
 GLUX_LOAD(GL_MESA_window_pos)
 GLUX_LOAD(GL_ARB_multi_draw_indirect)
 GLUX_LOAD(GL_SUN_global_alpha)
 GLUX_LOAD(GL_SGIX_async_pixel)
 GLUX_LOAD(GL_ARB_vertex_shader)
 GLUX_LOAD(GL_HP_occlusion_test)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_swap_barrier)
#endif
 GLUX_LOAD(GL_ARB_robustness_isolation)
 GLUX_LOAD(GL_EXT_texture_env_combine)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIS_shared_multisample)
#endif
 GLUX_LOAD(GL_ARB_tessellation_shader)
 GLUX_LOAD(GL_NV_gpu_program5)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_render_texture)
#endif
 GLUX_LOAD(GL_SGIX_convolution_accuracy)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_pixel_format)
#endif
 GLUX_LOAD(GL_ARB_texture_mirrored_repeat)
 GLUX_LOAD(GL_ARB_texture_compression)
 GLUX_LOAD(GL_ARB_texture_non_power_of_two)
 GLUX_LOAD(GL_ARB_vertex_buffer_object)
 GLUX_LOAD(GL_EXT_texture_sRGB)
 GLUX_LOAD(GL_NV_vertex_program2)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_fbconfig_packed_float)
#endif
 GLUX_LOAD(GL_NV_path_rendering)
 GLUX_LOAD(GL_EXT_draw_instanced)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_NV_float_buffer)
#endif
 GLUX_LOAD(GL_APPLE_rgb_422)
 GLUX_LOAD(GL_ARB_draw_indirect)
 GLUX_LOAD(GL_EXT_texture_integer)
 GLUX_LOAD(GL_EXT_fog_coord)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_OML_sync_control)
#endif
 GLUX_LOAD(GL_ARB_transform_feedback2)
 GLUX_LOAD(GL_ATI_vertex_array_object)
 GLUX_LOAD(GL_SGIX_fog_scale)
 GLUX_LOAD(GL_EXT_texture_cube_map)
 GLUX_LOAD(GL_EXT_blend_subtract)
 GLUX_LOAD(GL_SGIX_impact_pixel_texture)
 GLUX_LOAD(GL_EXT_texture_object)
 GLUX_LOAD(GL_ARB_explicit_attrib_location)
 GLUX_LOAD(GL_EXT_framebuffer_object)
 GLUX_LOAD(GL_AMD_transform_feedback3_lines_triangles)
 GLUX_LOAD(GL_AMD_draw_buffers_blend)
 GLUX_LOAD(GL_ARB_texture_buffer_range)
 GLUX_LOAD(GL_IBM_multimode_draw_arrays)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_video_source)
#endif
 GLUX_LOAD(GL_ARB_shading_language_include)
 GLUX_LOAD(GL_ARB_instanced_arrays)
 GLUX_LOAD(GL_EXT_framebuffer_multisample)
 GLUX_LOAD(GL_NV_shader_buffer_load)
 GLUX_LOAD(GL_ARB_texture_env_add)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_NV_copy_image)
#endif
 GLUX_LOAD(GL_ARB_occlusion_query)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_visual_info)
#endif
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_ARB_multisample)
#endif
 GLUX_LOAD(GL_EXT_stencil_clear_tag)
 GLUX_LOAD(GL_SUN_slice_accum)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_depth_float)
#endif
 GLUX_LOAD(GL_EXT_bindable_uniform)
 GLUX_LOAD(GL_ATI_texture_env_combine3)
 GLUX_LOAD(GL_SGIX_clipmap)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_create_context_es2_profile)
#endif
 GLUX_LOAD(GL_SGIX_ycrcb)
 GLUX_LOAD(GL_ARB_sync)
 GLUX_LOAD(GL_ARB_texture_view)
 GLUX_LOAD(GL_NV_register_combiners)
 GLUX_LOAD(GL_SUN_mesh_array)
 GLUX_LOAD(GL_NV_geometry_program4)
 GLUX_LOAD(GL_EXT_shadow_funcs)
 GLUX_LOAD(GL_EXT_texture)
 GLUX_LOAD(GL_ARB_explicit_uniform_location)
 GLUX_LOAD(GL_MESAX_texture_stack)
 GLUX_LOAD(GL_ARB_multisample)
 GLUX_LOAD(GL_EXT_texture_compression_rgtc)
 GLUX_LOAD(GL_EXT_framebuffer_blit)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_dmbuffer)
#endif
 GLUX_LOAD(GL_ARB_internalformat_query2)
 GLUX_LOAD(GL_SGIX_texture_multi_buffer)
 GLUX_LOAD(GL_EXT_timer_query)
 GLUX_LOAD(GL_APPLE_specular_vector)
 GLUX_LOAD(GL_ARB_compute_shader)
 GLUX_LOAD(GL_ARB_texture_query_lod)
 GLUX_LOAD(GL_ARB_compatibility)
 GLUX_LOAD(GL_ARB_fragment_program)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_hyperpipe)
#endif
 GLUX_LOAD(GL_AMD_vertex_shader_layer)
 GLUX_LOAD(GL_ARB_shader_image_size)
 GLUX_LOAD(GL_EXT_coordinate_frame)
 GLUX_LOAD(GL_EXT_blend_minmax)
 GLUX_LOAD(GL_NV_framebuffer_multisample_coverage)
 GLUX_LOAD(GL_EXT_point_parameters)
 GLUX_LOAD(GL_ARB_texture_swizzle)
 GLUX_LOAD(GL_EXT_packed_pixels)
 GLUX_LOAD(GL_MESA_resize_buffers)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_INTEL_swap_event)
#endif
 GLUX_LOAD(GL_NV_vertex_array_range2)
 GLUX_LOAD(GL_EXT_direct_state_access)
 GLUX_LOAD(GL_SGI_color_table)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_swap_control_tear)
#endif
 GLUX_LOAD(GL_ARB_texture_border_clamp)
 GLUX_LOAD(GL_ARB_texture_env_combine)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_display_color_table)
#endif
 GLUX_LOAD(GL_EXT_pixel_buffer_object)
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_swap_frame_usage)
#endif
 GLUX_LOAD(GL_ARB_fragment_program_shadow)
 GLUX_LOAD(GL_NV_vertex_program)
 GLUX_LOAD(GL_ARB_viewport_array)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_pixel_format)
#endif
 GLUX_LOAD(GL_EXT_gpu_shader4)
 GLUX_LOAD(GL_APPLE_row_bytes)
 GLUX_LOAD(GL_SGIS_texture_filter4)
 GLUX_LOAD(GL_SGIX_interlace)
 GLUX_LOAD(GL_ARB_program_interface_query)
 GLUX_LOAD(GL_NV_vertex_program3)
 GLUX_LOAD(GL_IBM_vertex_array_lists)
 GLUX_LOAD(GL_SGIS_fog_function)
 GLUX_LOAD(GL_EXT_clip_volume_hint)
 GLUX_LOAD(GL_SGIX_async_histogram)
 GLUX_LOAD(GL_SGI_texture_color_table)
 GLUX_LOAD(GL_SGIX_async)
 GLUX_LOAD(GL_SGIS_texture_lod)
 GLUX_LOAD(GL_ARB_invalidate_subdata)
#ifdef WIN32
 GLUX_LOAD(WGL_3DFX_multisample)
#endif
 GLUX_LOAD(GL_NV_texture_shader3)
 GLUX_LOAD(GL_SGIX_ir_instrument1)
 GLUX_LOAD(GL_NV_shader_buffer_store)
 GLUX_LOAD(GL_AMD_seamless_cubemap_per_texture)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_AMD_gpu_association)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_buffer_region)
#endif
 GLUX_LOAD(GL_GREMEDY_frame_terminator)
 GLUX_LOAD(GL_ARB_robust_buffer_access_behavior)
 GLUX_LOAD(GL_NV_vertex_array_range)
#ifdef WIN32
 GLUX_LOAD(WGL_AMD_gpu_association)
#endif
 GLUX_LOAD(GL_ARB_robustness)
 GLUX_LOAD(GL_ARB_shading_language_100)
 GLUX_LOAD(GL_AMD_multi_draw_indirect)
 GLUX_LOAD(GL_ARB_color_buffer_float)
 GLUX_LOAD(GL_SGIX_polynomial_ffd)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_visual_rating)
#endif
 GLUX_LOAD(GL_NV_pixel_data_range)
 GLUX_LOAD(GL_NV_fragment_program_option)
 GLUX_LOAD(GL_ATI_map_object_buffer)
 GLUX_LOAD(GL_NV_fence)
 GLUX_LOAD(GL_ARB_framebuffer_object)
 GLUX_LOAD(GL_SGIX_sprite)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_MESA_release_buffers)
#endif
 GLUX_LOAD(GL_EXT_texture_buffer_object)
 GLUX_LOAD(GL_NV_explicit_multisample)
 GLUX_LOAD(GL_EXT_vertex_shader)
 GLUX_LOAD(GL_EXT_texture_lod_bias)
 GLUX_LOAD(GL_ARB_gpu_shader5)
 GLUX_LOAD(GL_ARB_blend_func_extended)
 GLUX_LOAD(GL_ARB_texture_cube_map_array)
 GLUX_LOAD(GL_NV_texgen_reflection)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_MESA_pixmap_colormap)
#endif
 GLUX_LOAD(GL_ARB_stencil_texturing)
 GLUX_LOAD(GL_ARB_matrix_palette)
 GLUX_LOAD(GL_SGIX_instruments)
 GLUX_LOAD(GL_EXT_texture_env_add)
 GLUX_LOAD(GL_NV_texture_multisample)
 GLUX_LOAD(GL_NV_texture_shader2)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_DX_interop2)
#endif
 GLUX_LOAD(GL_SGIS_texture_color_mask)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_make_current_read)
#endif
 GLUX_LOAD(GL_EXT_paletted_texture)
 GLUX_LOAD(GL_OES_read_format)
 GLUX_LOAD(GL_ARB_sample_shading)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_render_depth_texture)
#endif
 GLUX_LOAD(GL_ATI_texture_float)
 GLUX_LOAD(GL_ARB_texture_multisample)
 GLUX_LOAD(GL_NV_texture_env_combine4)
 GLUX_LOAD(GL_NV_transform_feedback2)
 GLUX_LOAD(GL_EXT_cmyka)
 GLUX_LOAD(GL_EXT_422_pixels)
 GLUX_LOAD(GL_APPLE_vertex_array_object)
 GLUX_LOAD(GL_ARB_texture_env_crossbar)
 GLUX_LOAD(GL_NV_register_combiners2)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_extensions_string)
#endif
 GLUX_LOAD(GL_ARB_ES3_compatibility)
 GLUX_LOAD(GL_EXT_vertex_attrib_64bit)
 GLUX_LOAD(GL_ATI_draw_buffers)
 GLUX_LOAD(GL_ARB_depth_clamp)
 GLUX_LOAD(GL_EXT_shader_image_load_store)
 GLUX_LOAD(GL_EXT_pixel_transform_color_table)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_create_context_profile)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_create_context_robustness)
#endif
 GLUX_LOAD(GL_ARB_map_buffer_range)
 GLUX_LOAD(GL_ARB_copy_buffer)
 GLUX_LOAD(GL_SGIX_subsample)
 GLUX_LOAD(GL_NV_texture_shader)
 GLUX_LOAD(GL_EXT_vertex_array)
 GLUX_LOAD(GL_ARB_texture_storage)
 GLUX_LOAD(GL_EXT_depth_bounds_test)
#ifdef WIN32
 GLUX_LOAD(WGL_ATI_pixel_format_float)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_OML_sync_control)
#endif
 GLUX_LOAD(GL_SGIX_shadow)
 GLUX_LOAD(GL_AMD_vertex_shader_viewport_index)
 GLUX_LOAD(GL_ARB_texture_storage_multisample)
 GLUX_LOAD(GL_ARB_shader_precision)
 GLUX_LOAD(GL_ARB_texture_buffer_object)
 GLUX_LOAD(GL_NV_bindless_texture)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_vertex_array_range)
#endif
 GLUX_LOAD(GL_AMD_vertex_shader_tesselator)
 GLUX_LOAD(GL_NV_copy_image)
 GLUX_LOAD(GL_EXT_stencil_two_side)
 GLUX_LOAD(GL_SGIX_ycrcb_subsample)
 GLUX_LOAD(GL_AMD_performance_monitor)
 GLUX_LOAD(GL_SGIS_texture_edge_clamp)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_multisample)
#endif
 GLUX_LOAD(GL_ARB_vertex_attrib_64bit)
 GLUX_LOAD(GL_EXT_shared_texture_palette)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_pbuffer)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_NV_gpu_affinity)
#endif
 GLUX_LOAD(GL_KHR_debug)
 GLUX_LOAD(GL_NV_parameter_buffer_object)
 GLUX_LOAD(GL_INTEL_texture_scissor)
 GLUX_LOAD(GL_ATI_vertex_attrib_array_object)
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_genlock)
#endif
 GLUX_LOAD(GL_ARB_texture_compression_bptc)
 GLUX_LOAD(GL_REND_screen_coordinates)
 GLUX_LOAD(GL_APPLE_client_storage)
 GLUX_LOAD(GL_EXT_separate_shader_objects)
 GLUX_LOAD(GL_EXT_texture_sRGB_decode)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_import_context)
#endif
 GLUX_LOAD(GL_SUNX_constant_data)
 GLUX_LOAD(GL_OML_resample)
 GLUX_LOAD(GL_ARB_shader_texture_lod)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_swap_control)
#endif
 GLUX_LOAD(GL_NV_texture_barrier)
 GLUX_LOAD(GL_ARB_cl_event)
 GLUX_LOAD(GL_NV_present_video)
 GLUX_LOAD(GL_ARB_shader_atomic_counters)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_DX_interop)
#endif
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_framebuffer_sRGB)
#endif
 GLUX_LOAD(GL_SGIS_generate_mipmap)
 GLUX_LOAD(GL_ARB_texture_float)
 GLUX_LOAD(GL_NV_video_capture)
 GLUX_LOAD(GL_EXT_histogram)
 GLUX_LOAD(GL_ARB_texture_query_levels)
 GLUX_LOAD(GL_ARB_clear_buffer_object)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_3DFX_multisample)
#endif
 GLUX_LOAD(GL_ARB_texture_rg)
 GLUX_LOAD(GL_APPLE_ycbcr_422)
 GLUX_LOAD(GL_NV_shader_atomic_float)
 GLUX_LOAD(GL_ARB_map_buffer_alignment)
 GLUX_LOAD(GL_NV_blend_square)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_NV_swap_group)
#endif
 GLUX_LOAD(GL_EXT_x11_sync_object)
 GLUX_LOAD(GL_ARB_transpose_matrix)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_fbconfig)
#endif
 GLUX_LOAD(GL_OML_subsample)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_texture_from_pixmap)
#endif
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_video_resize)
#endif
 GLUX_LOAD(GL_ATI_envmap_bumpmap)
 GLUX_LOAD(GL_SGIX_texture_add_env)
 GLUX_LOAD(GL_EXT_index_array_formats)
 GLUX_LOAD(GL_ARB_shader_stencil_export)
 GLUX_LOAD(GL_EXT_convolution)
 GLUX_LOAD(GL_SGIS_sharpen_texture)
 GLUX_LOAD(GL_EXT_blend_color)
 GLUX_LOAD(GL_NV_texture_expand_normal)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_render_texture_rectangle)
#endif
 GLUX_LOAD(GL_NV_parameter_buffer_object2)
 GLUX_LOAD(GL_ARB_draw_buffers)
 GLUX_LOAD(GL_EXT_misc_attribute)
 GLUX_LOAD(GL_EXT_vertex_array_bgra)
 GLUX_LOAD(GL_ARB_framebuffer_sRGB)
 GLUX_LOAD(GL_EXT_texture3D)
 GLUX_LOAD(GL_NV_vertex_buffer_unified_memory)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_video_output)
#endif
 GLUX_LOAD(GL_INGR_palette_buffer)
 GLUX_LOAD(GL_ARB_transform_feedback_instanced)
 GLUX_LOAD(GL_NV_vertex_program1_1)
 GLUX_LOAD(GL_ARB_texture_buffer_object_rgb32)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_ARB_framebuffer_sRGB)
#endif
 GLUX_LOAD(GL_ARB_debug_output)
 GLUX_LOAD(GL_ARB_shadow_ambient)
 GLUX_LOAD(GL_PGI_vertex_hints)
 GLUX_LOAD(GL_APPLE_object_purgeable)
 GLUX_LOAD(GL_SGIX_depth_texture)
 GLUX_LOAD(GL_ARB_depth_texture)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_create_context)
#endif
 GLUX_LOAD(GL_ARB_vertex_attrib_binding)
 GLUX_LOAD(GL_HP_image_transform)
 GLUX_LOAD(GL_SGIX_depth_pass_instrument)
 GLUX_LOAD(GL_SGIS_multisample)
 GLUX_LOAD(GL_ARB_fragment_shader)
 GLUX_LOAD(GL_EXT_texture_shared_exponent)
 GLUX_LOAD(GL_SGIX_flush_raster)
 GLUX_LOAD(GL_ARB_texture_env_dot3)
 GLUX_LOAD(GL_NV_texture_compression_vtc)
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_swap_frame_lock)
#endif
 GLUX_LOAD(GL_ARB_conservative_depth)
 GLUX_LOAD(GL_EXT_abgr)
 GLUX_LOAD(GL_NV_tessellation_program5)
 GLUX_LOAD(GL_EXT_texture_compression_s3tc)
 GLUX_LOAD(GL_EXT_separate_specular_color)
 GLUX_LOAD(GL_SGIX_shadow_ambient)
 GLUX_LOAD(GL_NV_evaluators)
 GLUX_LOAD(GL_SGIX_framezoom)
 GLUX_LOAD(GL_EXT_index_func)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_video_out)
#endif
 GLUX_LOAD(GL_EXT_texture_mirror_clamp)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_swap_control_tear)
#endif
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_EXT_swap_control)
#endif
 GLUX_LOAD(GL_MESA_ycbcr_texture)
 GLUX_LOAD(GL_AMD_texture_texture4)
 GLUX_LOAD(GL_OML_interlace)
 GLUX_LOAD(GL_AMD_debug_output)
 GLUX_LOAD(GL_EXT_framebuffer_multisample_blit_scaled)
 GLUX_LOAD(GL_NV_vertex_program2_option)
 GLUX_LOAD(GL_NV_conditional_render)
 GLUX_LOAD(GL_ARB_fragment_layer_viewport)
#ifdef WIN32
 GLUX_LOAD(WGL_NV_copy_image)
#endif
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIS_multisample)
#endif
 GLUX_LOAD(GL_NV_vdpau_interop)
 GLUX_LOAD(GL_NV_fog_distance)
 GLUX_LOAD(GL_NV_half_float)
 GLUX_LOAD(GL_EXT_color_subtable)
 GLUX_LOAD(GL_NV_depth_buffer_float)
 GLUX_LOAD(GL_NV_packed_depth_stencil)
 GLUX_LOAD(GL_NV_float_buffer)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SUN_get_transparent_index)
#endif
 GLUX_LOAD(GL_SGIX_igloo_interface)
 GLUX_LOAD(GL_NV_gpu_program4)
 GLUX_LOAD(GL_NV_fragment_program2)
 GLUX_LOAD(GL_APPLE_float_pixels)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_pixel_format_float)
#endif
 GLUX_LOAD(GL_EXT_texture_perturb_normal)
 GLUX_LOAD(GL_ARB_geometry_shader4)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_ARB_vertex_buffer_object)
#endif
 GLUX_LOAD(GL_ARB_shader_image_load_store)
 GLUX_LOAD(GL_EXT_stencil_wrap)
 GLUX_LOAD(GL_ARB_seamless_cube_map)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGIX_swap_group)
#endif
 GLUX_LOAD(GL_ARB_sampler_objects)
 GLUX_LOAD(GL_EXT_secondary_color)
 GLUX_LOAD(GL_AMD_blend_minmax_factor)
 GLUX_LOAD(GL_EXT_texture_array)
 GLUX_LOAD(GL_ARB_window_pos)
 GLUX_LOAD(GL_AMD_stencil_operation_extended)
 GLUX_LOAD(GL_AMD_sparse_texture)
 GLUX_LOAD(GL_SGIS_point_parameters)
 GLUX_LOAD(GL_SGI_color_matrix)
 GLUX_LOAD(GL_EXT_blend_logic_op)
 GLUX_LOAD(GL_WIN_phong_shading)
 GLUX_LOAD(GL_IBM_texture_mirrored_repeat)
 GLUX_LOAD(GL_SGIX_reference_plane)
 GLUX_LOAD(GL_EXT_draw_buffers2)
 GLUX_LOAD(GL_EXT_transform_feedback)
 GLUX_LOAD(GL_ARB_gpu_shader_fp64)
 GLUX_LOAD(GL_NV_texture_rectangle)
 GLUX_LOAD(GL_3DFX_texture_compression_FXT1)
 GLUX_LOAD(GL_ATI_separate_stencil)
 GLUX_LOAD(GL_EXT_geometry_shader4)
#ifdef WIN32
 GLUX_LOAD(WGL_EXT_pbuffer)
#endif
 GLUX_LOAD(GL_ARB_arrays_of_arrays)
 GLUX_LOAD(GL_IBM_rasterpos_clip)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_NV_multisample_coverage)
#endif
 GLUX_LOAD(GL_ARB_uniform_buffer_object)
 GLUX_LOAD(GL_ARB_vertex_blend)
 GLUX_LOAD(GL_SGIX_fragment_lighting)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_NV_video_capture)
#endif
 GLUX_LOAD(GL_ARB_draw_instanced)
 GLUX_LOAD(GL_PGI_misc_hints)
 GLUX_LOAD(GL_SGIX_resample)
 GLUX_LOAD(GL_ARB_fragment_coord_conventions)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGI_video_sync)
#endif
 GLUX_LOAD(GL_EXT_subtexture)
 GLUX_LOAD(GL_HP_convolution_border_modes)
 GLUX_LOAD(GL_ATI_vertex_streams)
 GLUX_LOAD(GL_ARB_texture_compression_rgtc)
 GLUX_LOAD(GL_SGIS_point_line_texgen)
 GLUX_LOAD(GL_ARB_shader_objects)
 GLUX_LOAD(GL_SUN_triangle_list)
 GLUX_LOAD(GL_ARB_pixel_buffer_object)
 GLUX_LOAD(GL_EXT_light_texture)
 GLUX_LOAD(GL_NV_primitive_restart)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_SGI_swap_control)
#endif
 GLUX_LOAD(GL_ARB_draw_elements_base_vertex)
 GLUX_LOAD(GL_HP_texture_lighting)
 GLUX_LOAD(GL_ATI_meminfo)
 GLUX_LOAD(GL_INGR_color_clamp)
 GLUX_LOAD(GL_AMD_sample_positions)
 GLUX_LOAD(GL_EXT_blend_func_separate)
 GLUX_LOAD(GL_SGIS_pixel_texture)
 GLUX_LOAD(GL_ARB_shadow)
 GLUX_LOAD(GL_ARB_shader_storage_buffer_object)
 GLUX_LOAD(GL_SGI_depth_pass_instrument)
 GLUX_LOAD(GL_EXT_texture_env_dot3)
 GLUX_LOAD(GL_ATI_pn_triangles)
 GLUX_LOAD(GL_SGIS_texture_border_clamp)
 GLUX_LOAD(GL_ARB_texture_rectangle)
 GLUX_LOAD(GL_GREMEDY_string_marker)
 GLUX_LOAD(GL_ARB_imaging)
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_ARB_create_context_robustness)
#endif
 GLUX_LOAD(GL_SGIS_texture4D)
#ifdef WIN32
 GLUX_LOAD(WGL_ARB_make_current_read)
#endif
#if !(defined WIN32 || defined __APPLE__)
 GLUX_LOAD(GLX_NV_video_output)
#endif
 GLUX_LOAD(GL_ARB_vertex_type_2_10_10_10_rev)
 GLUX_LOAD(GL_AMD_name_gen_delete)
#ifdef WIN32
 GLUX_LOAD(WGL_I3D_image_buffer)
#endif
// --------------------------------------------------------
#endif
// --------------------------------------------------------
